name: URL Validation

on:
  pull_request:
    paths:
      - 'docs/schemas/**'
      - 'docs/*.md'

jobs:
  validate-urls:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Validate Documentation URLs
        run: |
          urls=(
            "https://xdebug.org/docs/trace"
          )

          for url in "${urls[@]}"; do
            status=$(curl -s -o /dev/null -w "%{http_code}" "$url")
            if [[ "$status" -ge 400 ]]; then
              echo "ERROR: $url ↦ HTTP $status"
              exit 1
            fi
            echo "OK:    $url"
          done
          
          # Check local files exist instead of GitHub Pages URLs
          files=(
            "docs/schemas/xdebug-debug.json"
            "docs/debug-guidelines.md"
          )
          
          for file in "${files[@]}"; do
            if [[ ! -f "$file" ]]; then
              echo "ERROR: File not found: $file"
              exit 1
            fi
            echo "OK:    $file (exists locally)"
          done