name: URL Validation

on:
  pull_request:
    paths:
      - 'docs/schemas/**'
      - 'docs/*.md'

jobs:
  validate-urls:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Validate Documentation URLs
        run: |
          urls=(
            "https://koriym.github.io/xdebug-mcp/schemas/xdebug-debug.json"
            "https://xdebug.org/docs/trace"
            "https://koriym.github.io/xdebug-mcp/debug-guidelines.md"
            "https://koriym.github.io/xdebug-mcp/ai-debugging-with-debugger.md"
          )

          for url in "${urls[@]}"; do
            status=$(curl -s -o /dev/null -w "%{http_code}" "$url")
            if [[ "$status" -ge 400 ]]; then
              echo "ERROR: $url ↦ HTTP $status"
              exit 1
            fi
            echo "OK:    $url"
          done